const main = async () => {
    try {
        // lets write some cool stuff
    } catch (err) {
        console.log("Not today ðŸ˜¢")
        process.exit(1);
    }
}

main()